#!/bin/sh /etc/rc.common

START=70

USE_PROCD=1
PROG=/usr/bin/prometheus-alertmanager
CONFFILE=/etc/prometheus-alertmanager.yml

start_service() {
        procd_open_instance
        procd_set_param command $PROG --config.file=$CONFFILE
        procd_set_param file $CONFFILE
        procd_set_param respawn
        procd_close_instance
}
